In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN'
application_df = application_df.drop(columns=['EIN'])
application_df.head()

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
name_count = application_df['NAME'].value_counts()
name_count[name_count > 50]

NAME
PARENT BOOSTER USA INC                                                1260
TOPS CLUB INC                                                          765
UNITED STATES BOWLING CONGRESS INC                                     700
WASHINGTON STATE UNIVERSITY                                            492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                        408
PTA TEXAS CONGRESS                                                     368
SOROPTIMIST INTERNATIONAL OF THE AMERICAS INC                          331
ALPHA PHI SIGMA                                                        313
TOASTMASTERS INTERNATIONAL                                             293
MOST WORSHIPFUL STRINGER FREE AND ACCEPTED MASONS                      287
LITTLE LEAGUE BASEBALL INC                                             277
INTERNATIONAL ASSOCIATION OF LIONS CLUBS                               266
MOMS CLUB                                                              210
INTERNATIONAL ASSOCIATION OF SHEET METAL AIR RAIL & TRANSPORTATION     206
AMERICAN ASSOCIATION OF UNIVERSITY WOMEN                               197
FARMERS EDUCATIONAL AND COOPERATIVE UNION OF AMERICA                   166
KNIGHTS OF COLUMBUS                                                    158
HABITAT FOR HUMANITY INTERNATIONAL INC                                 154
TENNESSEE ORDER OF THE EASTERN STAR                                    151
VETERANS OF FOREIGN WARS OF THE UNITED STATES AUXILIARY                144
PTA UTAH CONGRESS                                                      140
THE UNITED STATES PONY CLUBS INC                                       136
CIVITAN INTERNATIONAL                                                  131
SIGMA BETA DELTA INC                                                   127
HONOR SOCIETY OF PHI KAPPA PHI                                         107
MONTANA 4-H FOUNDATION INC                                             107
WASHINGTON STATE GRANGE                                                106
UNIVERSITY OF WYOMING                                                  105
DEMOLAY INTERNATIONAL                                                  104
SERTOMA INC                                                            103
AIR FORCE ASSOCIATION                                                   99
WORKERS UNITED                                                          97
GAMMA THETA UPSILON                                                     92
INTERNATIONAL ASSOCIATION OF FIRE FIGHTERS                              91
SOCIETY OF SAINT VINCENT DE PAUL COUNCIL OF LOS ANGELES                 87
ROTARY INTERNATIONAL                                                    84
CALIFORNIA GARDEN CLUBS INC                                             76
SWEET ADELINES INTERNATIONAL                                            73
DISABLED AMERICAN VETERANS                                              73
KLEIN SUPPORT GROUPS INC                                                69
CLEARCREEK I S D SUPPORT GROUPS                                         60
VFW AUXILIARY DEPARTMENT OF OKLAHOMA INC                                58
DEPARTMENT OF KANSAS LADIES AUXILIARY TO THE VFW OF THE US INC          57
CISD EDUCATIONAL SUPPORT GROUPS INC                                     57
SONS OF CONFEDERATE VETERANS INC                                        56
SLOW FOOD USA INC                                                       55
NATIONAL YOUNG MENS SERVICE LEAGUE                                      54
AMATEUR ATHLETIC UNION OF THE UNITED STATES                             52
LAMBDA THETA ALPHA                                                      52
Name: count, dtype: int64

In [4]:
name_types_to_replace = list(name_count[name_count < 50].index)

# Replace in dataframe
for name in name_types_to_replace:
    application_df['NAME'] = application_df['NAME'].replace(name,"Other")

# Check to make sure binning was successful
application_df['NAME'].value_counts()

NAME
Other                                                                 24545
PARENT BOOSTER USA INC                                                 1260
TOPS CLUB INC                                                           765
UNITED STATES BOWLING CONGRESS INC                                      700
WASHINGTON STATE UNIVERSITY                                             492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                         408
PTA TEXAS CONGRESS                                                      368
SOROPTIMIST INTERNATIONAL OF THE AMERICAS INC                           331
ALPHA PHI SIGMA                                                         313
TOASTMASTERS INTERNATIONAL                                              293
MOST WORSHIPFUL STRINGER FREE AND ACCEPTED MASONS                       287
LITTLE LEAGUE BASEBALL INC                                              277
INTERNATIONAL ASSOCIATION OF LIONS CLUBS                                266
MOMS CLUB                                                               210
INTERNATIONAL ASSOCIATION OF SHEET METAL AIR RAIL & TRANSPORTATION      206
AMERICAN ASSOCIATION OF UNIVERSITY WOMEN                                197
FARMERS EDUCATIONAL AND COOPERATIVE UNION OF AMERICA                    166
KNIGHTS OF COLUMBUS                                                     158
HABITAT FOR HUMANITY INTERNATIONAL INC                                  154
TENNESSEE ORDER OF THE EASTERN STAR                                     151
VETERANS OF FOREIGN WARS OF THE UNITED STATES AUXILIARY                 144
PTA UTAH CONGRESS                                                       140
THE UNITED STATES PONY CLUBS INC                                        136
CIVITAN INTERNATIONAL                                                   131
SIGMA BETA DELTA INC                                                    127
MONTANA 4-H FOUNDATION INC                                              107
HONOR SOCIETY OF PHI KAPPA PHI                                          107
WASHINGTON STATE GRANGE                                                 106
UNIVERSITY OF WYOMING                                                   105
DEMOLAY INTERNATIONAL                                                   104
SERTOMA INC                                                             103
AIR FORCE ASSOCIATION                                                    99
WORKERS UNITED                                                           97
GAMMA THETA UPSILON                                                      92
INTERNATIONAL ASSOCIATION OF FIRE FIGHTERS                               91
SOCIETY OF SAINT VINCENT DE PAUL COUNCIL OF LOS ANGELES                  87
ROTARY INTERNATIONAL                                                     84
CALIFORNIA GARDEN CLUBS INC                                              76
SWEET ADELINES INTERNATIONAL                                             73
DISABLED AMERICAN VETERANS                                               73
KLEIN SUPPORT GROUPS INC                                                 69
CLEARCREEK I S D SUPPORT GROUPS                                          60
VFW AUXILIARY DEPARTMENT OF OKLAHOMA INC                                 58
CISD EDUCATIONAL SUPPORT GROUPS INC                                      57
DEPARTMENT OF KANSAS LADIES AUXILIARY TO THE VFW OF THE US INC           57
SONS OF CONFEDERATE VETERANS INC                                         56
SLOW FOOD USA INC                                                        55
NATIONAL YOUNG MENS SERVICE LEAGUE                                       54
AMATEUR ATHLETIC UNION OF THE UNITED STATES                              52
LAMBDA THETA ALPHA                                                       52
UNITED FEDERATION OF DOLL CLUBS INC                                      50
UNIVERSITY OF FLORIDA                                                    50
Name: count, dtype: int64

In [5]:
# Look at APPLICATION_TYPE value counts for binning
application_type_count = application_df['APPLICATION_TYPE'].value_counts()
application_type_count

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_type_count[application_type_count < 20].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
T13         66
Other       27
T12         27
Name: count, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts for binning
classification_count = application_df['CLASSIFICATION'].value_counts()
classification_count[classification_count > 1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_count[classification_count < 100].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: count, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
application_dummies = pd.get_dummies(application_df)
application_dummies.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_AIR FORCE ASSOCIATION,NAME_ALPHA PHI SIGMA,NAME_AMATEUR ATHLETIC UNION OF THE UNITED STATES,NAME_AMATEUR ATHLETIC UNION OF THE UNITED STATES INC,NAME_AMERICAN ASSOCIATION OF UNIVERSITY WOMEN,NAME_CALIFORNIA GARDEN CLUBS INC,NAME_CISD EDUCATIONAL SUPPORT GROUPS INC,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [10]:
# Split our preprocessed data into our features and target arrays
y = application_dummies['IS_SUCCESSFUL'].values

X = application_dummies.drop(columns='IS_SUCCESSFUL').values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    random_state=1)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [12]:
num_input_features = len(X_train_scaled[1])
print(f"Number of Input Features : {num_input_features}")

Number of Input Features : 104

Compile, Train and Evaluate the Model

In [13]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
hidden_nodes_layer1 =  150
hidden_nodes_layer2 = 100
hidden_nodes_layer3 = 50
hidden_nodes_layer4 = 25

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=num_input_features, activation="relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="relu"))

# Fourth hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer4, activation="tanh"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

c:\Users\matth\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:86: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 150)            │        15,750 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 100)            │        15,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 50)             │         5,050 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 25)             │         1,275 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            26 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 37,201 (145.32 KB)

 Trainable params: 37,201 (145.32 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [15]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 989us/step - accuracy: 0.7340 - loss: 0.5208
Epoch 2/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7651 - loss: 0.4784
Epoch 3/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 855us/step - accuracy: 0.7648 - loss: 0.4763
Epoch 4/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 896us/step - accuracy: 0.7719 - loss: 0.4705
Epoch 5/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 913us/step - accuracy: 0.7710 - loss: 0.4656
Epoch 6/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 894us/step - accuracy: 0.7731 - loss: 0.4686
Epoch 7/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 898us/step - accuracy: 0.7722 - loss: 0.4648
Epoch 8/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 887us/step - accuracy: 0.7731 - loss: 0.4651
Epoch 9/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 883us/step - accuracy: 0.7716 - loss: 0.4651
Epoch 10/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 867us/step - accuracy: 0.7717 - loss: 0.4668
Epoch 11/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 938us/step - accuracy: 0.7701 - loss: 0.4700
Epoch 12/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 918us/step - accuracy: 0.7706 - loss: 0.4632
Epoch 13/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 905us/step - accuracy: 0.7784 - loss: 0.4604
Epoch 14/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 912us/step - accuracy: 0.7761 - loss: 0.4590
Epoch 15/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 903us/step - accuracy: 0.7682 - loss: 0.4719
Epoch 16/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 916us/step - accuracy: 0.7736 - loss: 0.4663
Epoch 17/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 888us/step - accuracy: 0.7772 - loss: 0.4585
Epoch 18/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 871us/step - accuracy: 0.7725 - loss: 0.4621
Epoch 19/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 901us/step - accuracy: 0.7730 - loss: 0.4629
Epoch 20/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 890us/step - accuracy: 0.7755 - loss: 0.4616
Epoch 21/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 869us/step - accuracy: 0.7773 - loss: 0.4571
Epoch 22/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 886us/step - accuracy: 0.7786 - loss: 0.4569
Epoch 23/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 877us/step - accuracy: 0.7682 - loss: 0.4664
Epoch 24/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 865us/step - accuracy: 0.7767 - loss: 0.4589
Epoch 25/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 907us/step - accuracy: 0.7769 - loss: 0.4538
Epoch 26/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 951us/step - accuracy: 0.7714 - loss: 0.4585
Epoch 27/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 901us/step - accuracy: 0.7754 - loss: 0.4600
Epoch 28/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 906us/step - accuracy: 0.7754 - loss: 0.4583
Epoch 29/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 906us/step - accuracy: 0.7769 - loss: 0.4575
Epoch 30/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 904us/step - accuracy: 0.7751 - loss: 0.4573
Epoch 31/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 946us/step - accuracy: 0.7767 - loss: 0.4560
Epoch 32/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 867us/step - accuracy: 0.7755 - loss: 0.4560
Epoch 33/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 938us/step - accuracy: 0.7708 - loss: 0.4635
Epoch 34/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 947us/step - accuracy: 0.7810 - loss: 0.4513
Epoch 35/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 907us/step - accuracy: 0.7806 - loss: 0.4549
Epoch 36/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 921us/step - accuracy: 0.7729 - loss: 0.4599
Epoch 37/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7810 - loss: 0.4504
Epoch 38/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 953us/step - accuracy: 0.7761 - loss: 0.4564
Epoch 39/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 989us/step - accuracy: 0.7779 - loss: 0.4536
Epoch 40/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 918us/step - accuracy: 0.7763 - loss: 0.4542
Epoch 41/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 954us/step - accuracy: 0.7749 - loss: 0.4585
Epoch 42/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 894us/step - accuracy: 0.7790 - loss: 0.4518
Epoch 43/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7807 - loss: 0.4524
Epoch 44/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7765 - loss: 0.4557
Epoch 45/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7772 - loss: 0.4534
Epoch 46/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 980us/step - accuracy: 0.7771 - loss: 0.4568
Epoch 47/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 942us/step - accuracy: 0.7720 - loss: 0.4576
Epoch 48/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 928us/step - accuracy: 0.7774 - loss: 0.4554
Epoch 49/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 888us/step - accuracy: 0.7743 - loss: 0.4604
Epoch 50/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 873us/step - accuracy: 0.7735 - loss: 0.4554
Epoch 51/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 893us/step - accuracy: 0.7778 - loss: 0.4529
Epoch 52/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 885us/step - accuracy: 0.7748 - loss: 0.4607
Epoch 53/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 884us/step - accuracy: 0.7804 - loss: 0.4513
Epoch 54/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 908us/step - accuracy: 0.7779 - loss: 0.4535
Epoch 55/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 930us/step - accuracy: 0.7807 - loss: 0.4508
Epoch 56/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7803 - loss: 0.4518
Epoch 57/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 895us/step - accuracy: 0.7826 - loss: 0.4499
Epoch 58/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 915us/step - accuracy: 0.7745 - loss: 0.4554
Epoch 59/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 875us/step - accuracy: 0.7767 - loss: 0.4560
Epoch 60/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 906us/step - accuracy: 0.7763 - loss: 0.4558
Epoch 61/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 915us/step - accuracy: 0.7757 - loss: 0.4565
Epoch 62/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 904us/step - accuracy: 0.7764 - loss: 0.4569
Epoch 63/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 878us/step - accuracy: 0.7790 - loss: 0.4534
Epoch 64/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 872us/step - accuracy: 0.7769 - loss: 0.4563
Epoch 65/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 907us/step - accuracy: 0.7777 - loss: 0.4498
Epoch 66/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 923us/step - accuracy: 0.7766 - loss: 0.4525
Epoch 67/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 900us/step - accuracy: 0.7786 - loss: 0.4510
Epoch 68/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 874us/step - accuracy: 0.7739 - loss: 0.4574
Epoch 69/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 908us/step - accuracy: 0.7736 - loss: 0.4556
Epoch 70/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 904us/step - accuracy: 0.7782 - loss: 0.4506
Epoch 71/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 901us/step - accuracy: 0.7718 - loss: 0.4568
Epoch 72/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 898us/step - accuracy: 0.7780 - loss: 0.4510
Epoch 73/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 851us/step - accuracy: 0.7773 - loss: 0.4548
Epoch 74/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 871us/step - accuracy: 0.7754 - loss: 0.4555
Epoch 75/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 882us/step - accuracy: 0.7788 - loss: 0.4521
Epoch 76/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 891us/step - accuracy: 0.7758 - loss: 0.4535
Epoch 77/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 926us/step - accuracy: 0.7813 - loss: 0.4483
Epoch 78/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 954us/step - accuracy: 0.7782 - loss: 0.4535
Epoch 79/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 857us/step - accuracy: 0.7731 - loss: 0.4597
Epoch 80/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 907us/step - accuracy: 0.7826 - loss: 0.4492
Epoch 81/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 932us/step - accuracy: 0.7787 - loss: 0.4501
Epoch 82/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 876us/step - accuracy: 0.7783 - loss: 0.4555
Epoch 83/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 899us/step - accuracy: 0.7808 - loss: 0.4517
Epoch 84/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 860us/step - accuracy: 0.7750 - loss: 0.4574
Epoch 85/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 879us/step - accuracy: 0.7745 - loss: 0.4557
Epoch 86/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 861us/step - accuracy: 0.7768 - loss: 0.4539
Epoch 87/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 856us/step - accuracy: 0.7759 - loss: 0.4569
Epoch 88/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 885us/step - accuracy: 0.7773 - loss: 0.4603
Epoch 89/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 856us/step - accuracy: 0.7737 - loss: 0.4598
Epoch 90/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 863us/step - accuracy: 0.7763 - loss: 0.4592
Epoch 91/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 906us/step - accuracy: 0.7814 - loss: 0.4501
Epoch 92/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 847us/step - accuracy: 0.7782 - loss: 0.4565
Epoch 93/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 852us/step - accuracy: 0.7734 - loss: 0.4590
Epoch 94/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 849us/step - accuracy: 0.7816 - loss: 0.4483
Epoch 95/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 830us/step - accuracy: 0.7796 - loss: 0.4523
Epoch 96/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 826us/step - accuracy: 0.7755 - loss: 0.4532
Epoch 97/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 837us/step - accuracy: 0.7777 - loss: 0.4579
Epoch 98/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 832us/step - accuracy: 0.7799 - loss: 0.4519
Epoch 99/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 841us/step - accuracy: 0.7766 - loss: 0.4573
Epoch 100/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 823us/step - accuracy: 0.7788 - loss: 0.4521

In [16]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - 919us/step - accuracy: 0.7638 - loss: 0.4932
Loss: 0.49320077896118164, Accuracy: 0.7638484239578247

In [17]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity_Optimization.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.